defaultChannel: 'OOC'

Channels:
  OOC:
    name: 'Talking in OOC chat'
    list_style: '[OOC] The OOC chat channel - Global radius'
    radius: 0
    ignore_world: true
    format: '[OOC] %player_name% >> %message%'
    muteable: true

  IC:
    name: 'Talking in IC chat'
    list_style: '[IC] The IC chat channel - 20 block radius'
    radius: 20
    ignore_world: false
    format: '[IC] %player_name% >> %message%'
    muteable: true
