name: ChatPlugin
main: com.github.DarkVanityOfLight.ChattPlugin.Main
version: 1.3.0
author: DarkVanityOfLight
api-version: '1.16'

permissions:
  chatplugin.spy:
    description: let you see all chats without range restrictions using /spy
    default: false