name: ChatPlugin
main: com.github.DarkVanityOfLight.ChattPlugin.Main
version: 1.4.6
author: DarkVanityOfLight
api-version: '1.16'
softdepend: [Factions]

permissions:
  chatplugin.spy:
    description: let you see all chats without range restrictions using /spy
    default: false

commands:
  spy:
    description: Spy on all channels without range restriction
    usage: /spy
    permission: chatplugin.spy
    permission-message: Fuck of you are not allowed to spy on people

  mute:
    description: Mute one or more given channels
    usage: /mute <chanel> <names>